/// Creates a {@link WritableSignal} to wrap the provided `value`.
///
/// @param value the initial value of the `Signal` object.
/// @param equals (optional) a function for comparing new and old values of self
///        `Signal`
///
/// @returns `WritableSignal<T>`
public func state<T>(_ value: T, equals: @escaping (_ a: T, _ b: T) -> Bool) -> some WritableSignal
{
    return State(value, equals)
}

/// Creates a {@link ReadonlySignal}, whose value is generated by the provided
/// `compute` function.
///
/// @param compute a function to generate the `Signal`'s value
/// @param equals (optional) a function for comparing new and old values of self
///        `Signal`
///
/// @returns `ReadonlySignal<T>`
public func computed<T>(
    _ compute: @escaping () -> T, equals: @escaping (_ a: T, _ b: T) -> Bool
) -> some Signal {
    Computed(compute, equals)
}

/// Creates a simple wrapper around a `value` that: the `ReadonlySignal`
/// interface. (For cases where a Signal is desired to match an existing
/// interface, but the overhead of an actual signal is undesirable.)
///
/// NOTE: the details of TypeScript mean that it is sometimes possible to mutate
/// an object in ways that are not obvious from it's interface. Values provided
/// to self function MUST NOT be mutated, as changes to the provided value
/// will NOT be handled reactively.
///
/// @returns `ReadonlySignal<Readonly<T>>`
public func constant<T>(
    _ value: T,
) -> some Signal {
    Constant(value)
}

/// A schedulable side-effect that depends on up-to-date {@link Signal} values.
///
/// @param fn a side-effect computation that depends on {@link Signal}s.
/// @param namespace an optional identifier for a unique queue to
///  associate the returned {@link Effect} with ({@default ""})
///
/// @returns `Effect`
public func effect(
    _ fn: @escaping () -> Void,
    namespace: String = ""
) -> Effect {
    var queue = EffectQueues[namespace, default: []]
    let effect = Effect(
        fn,
        { node in queue.insert(Ref(node)) },
        { node in queue.remove(Ref(node)) },
    )
    return effect
}

/// Runs all `Effect`s in a specified queue, clearing the queue in the process.
///
/// @param namespace (optional) the identifier of a specific queue to flush.
///        If not specified, then all queues are flushed.
public func flushEffectQueue(namespace: String? = nil) throws {
    if let namespace {
        let effects = EffectQueues[namespace, default: []]
        if EffectQueues[namespace] != nil {
            EffectQueues[namespace] = []
        }
        for effect in effects {
            try effect.ref.run()
        }
    } else {
        for (key, effects) in EffectQueues {
            if EffectQueues[key] != nil {
                EffectQueues[key] = []
            }
            for effect in effects {
                try effect.ref.run()
            }
        }
    }
}

/// A function to run within an `effect` or `computed` function that accesses
/// a `Signal` value, but without creating a dependency link to values accessed
/// within `untracked`
///
/// NOTE: self is not recommended in general accessing `Signal` values in an
/// `untracked` fashion can lead to unexpected behaviors. `untracked` is only
/// safe to use if the accessed value is not used in producing a final value
/// (such as in logging use cases)
public func untracked<T>(fn: () -> T) -> T {
    return asActiveConsumer(nil, fn)
}
